# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from np_chatbot.youtube.proto import stream_list_pb2 as stream__list__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in stream_list_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class V3DataLiveChatMessageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamList = channel.unary_stream(
                '/youtube.api.v3.V3DataLiveChatMessageService/StreamList',
                request_serializer=stream__list__pb2.LiveChatMessageListRequest.SerializeToString,
                response_deserializer=stream__list__pb2.LiveChatMessageListResponse.FromString,
                _registered_method=True)


class V3DataLiveChatMessageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_V3DataLiveChatMessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamList': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamList,
                    request_deserializer=stream__list__pb2.LiveChatMessageListRequest.FromString,
                    response_serializer=stream__list__pb2.LiveChatMessageListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'youtube.api.v3.V3DataLiveChatMessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('youtube.api.v3.V3DataLiveChatMessageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class V3DataLiveChatMessageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/youtube.api.v3.V3DataLiveChatMessageService/StreamList',
            stream__list__pb2.LiveChatMessageListRequest.SerializeToString,
            stream__list__pb2.LiveChatMessageListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
